from django.urls import path

from apps.internal_admin.views import (
    AdminChapterBulkUploadView,
    AdminChapterDetailView,
    AdminChapterListCreateView,
    AdminConceptBulkUploadView,
    AdminExamDetailView,
    AdminExamListCreateView,
    AdminQuestionAiGenerateView,
    AdminQuestionBulkUploadView,
    AdminQuestionJsonImportView,
    AdminQuestionGeneratePreviewView,
    AdminQuestionSaveGeneratedView,
    AdminConceptDetailView,
    AdminConceptListCreateView,
    AdminDashboardView,
    AdminQuestionDetailView,
    AdminQuestionListCreateView,
    AdminSubjectDetailView,
    AdminSubjectListCreateView,
    AdminTemplateDetailView,
    AdminTemplateJsonImportView,
    AdminTemplateListCreateView,
    AdminUserDetailView,
    AdminUserListCreateView,
)


urlpatterns = [
    path("dashboard", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("users", AdminUserListCreateView.as_view(), name="admin-users"),
    path("users/<uuid:user_id>", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("exams", AdminExamListCreateView.as_view(), name="admin-exams"),
    path("exams/<uuid:exam_id>", AdminExamDetailView.as_view(), name="admin-exam-detail"),
    path("subjects", AdminSubjectListCreateView.as_view(), name="admin-subjects"),
    path("subjects/<uuid:subject_id>", AdminSubjectDetailView.as_view(), name="admin-subject-detail"),
    path("chapters", AdminChapterListCreateView.as_view(), name="admin-chapters"),
    path("chapters/bulk-upload", AdminChapterBulkUploadView.as_view(), name="admin-chapter-bulk-upload"),
    path("chapters/<uuid:chapter_id>", AdminChapterDetailView.as_view(), name="admin-chapter-detail"),
    path("concepts", AdminConceptListCreateView.as_view(), name="admin-concepts"),
    path("concepts/bulk-upload", AdminConceptBulkUploadView.as_view(), name="admin-concept-bulk-upload"),
    path("concepts/<uuid:concept_id>", AdminConceptDetailView.as_view(), name="admin-concept-detail"),
    path("templates", AdminTemplateListCreateView.as_view(), name="admin-templates"),
    path("templates/import-json", AdminTemplateJsonImportView.as_view(), name="admin-template-json-import"),
    path("templates/<uuid:template_id>", AdminTemplateDetailView.as_view(), name="admin-template-detail"),
    path("questions", AdminQuestionListCreateView.as_view(), name="admin-questions"),
    path("questions/bulk-upload", AdminQuestionBulkUploadView.as_view(), name="admin-question-bulk-upload"),
    path("questions/import-json", AdminQuestionJsonImportView.as_view(), name="admin-question-json-import"),
    path("questions/generate-preview", AdminQuestionGeneratePreviewView.as_view(), name="admin-question-generate-preview"),
    path("questions/save-generated", AdminQuestionSaveGeneratedView.as_view(), name="admin-question-save-generated"),
    path("questions/generate-ai", AdminQuestionAiGenerateView.as_view(), name="admin-question-ai-generate"),
    path("questions/<uuid:question_id>", AdminQuestionDetailView.as_view(), name="admin-question-detail"),
]
