# Generated by Django 6.0.3 on 2026-03-12 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardians', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardianstudentlink',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='guardians.guardianprofile'),
        ),
        migrations.AddField(
            model_name='guardianstudentlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='guardianstudentlink',
            constraint=models.UniqueConstraint(fields=('guardian', 'student'), name='unique_guardian_student_link'),
        ),
    ]
