# Generated by Django 6.0.3 on 2026-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_ai_exam_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
    ]
