# Generated by Django 6.0.3 on 2026-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentprofile_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='profile-images/'),
        ),
    ]
