# Generated by Django 6.0.3 on 2026-03-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.concept'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='diagnostics.question'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='diagnostics.question'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='diagnostics.questionoption'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.subject'),
        ),
        migrations.AddField(
            model_name='concept',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='diagnostics.subject'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to='diagnostics.subject'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.testattempt'),
        ),
        migrations.AddConstraint(
            model_name='conceptmastery',
            constraint=models.UniqueConstraint(fields=('student', 'concept'), name='unique_student_concept_mastery'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question', 'display_order'), name='unique_option_order_per_question'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='unique_concept_slug_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
    ]
