# Generated by Django 6.0.3 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exam_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
