# Generated by Django 6.0.3 on 2026-03-14

from django.db import migrations, models


def convert_exam_type_to_list(apps, schema_editor):
    Question = apps.get_model("diagnostics", "Question")
    for question in Question.objects.all():
        value = question.exam_type
        if isinstance(value, list):
            normalized = [item for item in value if item]
        elif value:
            normalized = [value]
        else:
            normalized = []
        question.exam_type = normalized
        question.save(update_fields=["exam_type"])


def convert_exam_type_to_string(apps, schema_editor):
    Question = apps.get_model("diagnostics", "Question")
    for question in Question.objects.all():
        value = question.exam_type
        if isinstance(value, list):
            normalized = value[0] if value else ""
        else:
            normalized = value or ""
        question.exam_type = normalized
        question.save(update_fields=["exam_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0003_question_exam_type"),
    ]

    operations = [
        migrations.RunPython(convert_exam_type_to_list, convert_exam_type_to_string),
        migrations.AlterField(
            model_name="question",
            name="exam_type",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
