# Generated by Django 6.0.3 on 2026-03-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0004_question_exam_type_multiselect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=20,
            ),
        ),
    ]
