# Generated by Django 6.0.3 on 2026-03-14 16:33

import uuid
from django.db import migrations, models
from django.utils.text import slugify


def seed_exam_links(apps, schema_editor):
    Exam = apps.get_model("diagnostics", "Exam")
    Subject = apps.get_model("diagnostics", "Subject")
    Concept = apps.get_model("diagnostics", "Concept")
    Question = apps.get_model("diagnostics", "Question")

    def get_or_create_exam(name):
        base_slug = slugify(name or "")[:140] or "exam"
        candidate = base_slug
        counter = 2
        while Exam.objects.filter(slug=candidate).exists():
            suffix = f"-{counter}"
            candidate = f"{base_slug[: max(1, 140 - len(suffix))]}{suffix}"
            counter += 1
        exam, created = Exam.objects.get_or_create(name=name, defaults={"slug": candidate})
        return exam

    question_exam_map = {}
    for question in Question.objects.all():
        exam_names = [value for value in (question.exam_type or []) if value]
        if not exam_names:
            continue
        exams = [get_or_create_exam(name) for name in exam_names]
        question.exams.set(exams)
        question_exam_map[question.id] = exams

    for subject in Subject.objects.all():
        exam_ids = {
            exam.id
            for question in Question.objects.filter(subject_id=subject.id).prefetch_related("exams")
            for exam in question.exams.all()
        }
        if exam_ids:
            subject.exams.set(Exam.objects.filter(id__in=exam_ids))

    for concept in Concept.objects.all():
        exam_ids = {
            exam.id
            for question in Question.objects.filter(concept_id=concept.id).prefetch_related("exams")
            for exam in question.exams.all()
        }
        if exam_ids:
            concept.exams.set(Exam.objects.filter(id__in=exam_ids))


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_question_status_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='concepts', to='diagnostics.exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='questions', to='diagnostics.exam'),
        ),
        migrations.AddField(
            model_name='subject',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='diagnostics.exam'),
        ),
        migrations.RunPython(seed_exam_links, migrations.RunPython.noop),
    ]
