# Generated by Codex on 2026-03-15

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def seed_default_chapters(apps, schema_editor):
    Subject = apps.get_model("diagnostics", "Subject")
    Chapter = apps.get_model("diagnostics", "Chapter")
    Concept = apps.get_model("diagnostics", "Concept")

    for subject in Subject.objects.all():
        base_name = "General"
        base_slug = slugify(base_name)[:160] or "general"
        candidate = base_slug
        counter = 2
        while Chapter.objects.filter(subject_id=subject.id, slug=candidate).exists():
            suffix = f"-{counter}"
            candidate = f"{base_slug[: max(1, 160 - len(suffix))]}{suffix}"
            counter += 1

        chapter = Chapter.objects.create(
            subject_id=subject.id,
            name=base_name,
            slug=candidate,
            description="Auto-created during chapter migration.",
        )
        chapter.exams.set(subject.exams.all())
        Concept.objects.filter(subject_id=subject.id, chapter__isnull=True).update(chapter_id=chapter.id)


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0006_exam_concept_exams_question_exams_subject_exams"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("exams", models.ManyToManyField(blank=True, related_name="chapters", to="diagnostics.exam")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chapters", to="diagnostics.subject")),
            ],
            options={
                "ordering": ["subject__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="concept",
            name="chapter",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="concepts", to="diagnostics.chapter"),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(fields=("subject", "slug"), name="unique_chapter_slug_per_subject"),
        ),
        migrations.RunPython(seed_default_chapters, migrations.RunPython.noop),
    ]
