# Generated by Django 6.0.3 on 2026-03-18 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_testattempt_exam'),
        ('students', '0005_studentprofile_ai_exam_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='retest_price',
            field=models.DecimalField(decimal_places=2, default='10.00', max_digits=8),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='learning_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='access_mode',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='last_saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='unanswered_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='wrong_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('provider', models.CharField(blank=True, default='manual', max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='diagnostics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='students.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='diagnostics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttemptQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='diagnostics.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='diagnostics.question')),
            ],
            options={
                'ordering': ['display_order'],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_attempt_question'), models.UniqueConstraint(fields=('attempt', 'display_order'), name='unique_attempt_question_order')],
            },
        ),
        migrations.CreateModel(
            name='TestEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('free_attempt_used', models.BooleanField(default=False)),
                ('paid_attempt_credits', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_entitlements', to='diagnostics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_entitlements', to='students.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_entitlements', to='diagnostics.subject')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_student_exam_subject_entitlement')],
            },
        ),
    ]
