# Generated by Django 6.0.3 on 2026-03-19 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0009_exam_is_active_exam_retest_price_subject_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("template_type", models.CharField(choices=[("logic", "Logic"), ("word", "Word"), ("multi_concept", "Multi-concept")], default="logic", max_length=30)),
                ("difficulty", models.CharField(choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")], default="medium", max_length=20)),
                ("template_text", models.TextField()),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("formula", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active")], default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="templates", to="diagnostics.concept")),
                ("secondary_concept", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="secondary_templates", to="diagnostics.concept")),
            ],
            options={"ordering": ["concept__name", "difficulty", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="question",
            name="generation_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="question",
            name="generation_source",
            field=models.CharField(choices=[("manual", "Manual"), ("generated", "Generated")], default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="question",
            name="secondary_concept",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="secondary_questions", to="diagnostics.concept"),
        ),
        migrations.AddField(
            model_name="question",
            name="template",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="generated_questions", to="diagnostics.questiontemplate"),
        ),
    ]
