# Generated by Django 6.0.3 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0010_questiontemplate_question_generation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontemplate",
            name="question_type",
            field=models.CharField(
                choices=[("mcq_single", "Single Correct MCQ"), ("mcq_multi", "Multiple Correct MCQ"), ("numeric", "Numeric")],
                default="mcq_single",
                max_length=30,
            ),
        ),
    ]
