# Generated by Django 6.0.3 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0011_questiontemplate_question_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="questiontemplate",
            name="constraints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="correct_answer_formula",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="distractor_logic",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="expected_time_sec",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="questiontemplate",
            name="jee_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
