# Generated by Django 6.0.3 on 2026-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0014_exam_exam_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontemplate',
            name='template_type',
            field=models.CharField(choices=[('logic', 'Logic'), ('word', 'Word'), ('multi_concept', 'Multi-concept'), ('logic_reverse_constraint', 'Logic Reverse Constraint')], default='logic', max_length=30),
        ),
    ]
