# Generated by Django 6.0.3 on 2026-03-12 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('health_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('consistency_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accuracy_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coverage_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
