# Generated by Django 6.0.3 on 2026-03-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_health', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninghealthsnapshot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_health_snapshots', to='students.studentprofile'),
        ),
        migrations.AddConstraint(
            model_name='learninghealthsnapshot',
            constraint=models.UniqueConstraint(fields=('student', 'snapshot_date'), name='unique_student_health_snapshot_date'),
        ),
    ]
