# Generated by Django 6.0.3 on 2026-03-19 08:42

import django.db.models.deletion
import uuid
from secrets import choice
from django.conf import settings
from django.db import migrations, models


REFERRAL_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def generate_referral_code(length=8):
    return "".join(choice(REFERRAL_CODE_ALPHABET) for _ in range(length))


def populate_referral_codes(apps, schema_editor):
    User = apps.get_model("users", "User")
    existing_codes = set(User.objects.exclude(referral_code="").values_list("referral_code", flat=True))

    for user in User.objects.filter(referral_code="").iterator():
        code = generate_referral_code()
        while code in existing_codes:
            code = generate_referral_code()
        user.referral_code = code
        user.save(update_fields=["referral_code"])
        existing_codes.add(code)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_provider_user_google_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_login_bonus', models.PositiveIntegerField(default=1000)),
                ('referral_bonus', models.PositiveIntegerField(default=200)),
                ('weak_topic_unlock_cost', models.PositiveIntegerField(default=25)),
                ('timer_reset_cost', models.PositiveIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='token_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_tokens_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('welcome_bonus', 'Welcome Bonus'), ('referral_bonus', 'Referral Bonus'), ('admin_adjustment', 'Admin Adjustment'), ('weak_topic_unlock', 'Weak Topic Unlock'), ('timer_reset', 'Timer Reset')], max_length=50)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_token_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
