# Generated by Django 6.0.3 on 2026-03-20 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tokentopuppurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='transaction_type',
            field=models.CharField(choices=[('welcome_bonus', 'Welcome Bonus'), ('referral_bonus', 'Referral Bonus'), ('admin_adjustment', 'Admin Adjustment'), ('weak_topic_unlock', 'Weak Topic Unlock'), ('timer_reset', 'Timer Reset'), ('token_topup', 'Token Top-up')], max_length=50),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expo_push_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_registered_at', models.DateTimeField(auto_now=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_registered_at', '-created_at'],
            },
        ),
    ]
