# Generated by Django 6.0.3 on 2026-03-12 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leaderboard_type', models.CharField(max_length=30)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rank_position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['leaderboard_type', 'rank_position'],
            },
        ),
    ]
